# Generated by Django 6.0.3 on 2026-06-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='birth',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'doctor'), ('PATIENT', 'Patient'), ('RECEPTIONIST', 'Receptionist')], default='PATIENT', max_length=20),
        ),
    ]
